### ISSUE TITLE
Git diff of nested directory

### ISSUE THREAD

**Issue by vweevers** [novemberborn/package-hash#5]
Currently, a git diff is only included [if the directory is a repository](https://github.com/novemberborn/package-hash/blob/a1102d19f7a9f9bd58db50e2a21534fafba66f8e/src/index.js#L35):

> Force the GIT_DIR to prevent git from diffing a parent repository in case the directory isn't actually a repository.

However, in a monorepo, when you want the hash of a nested package (`packages/beep/package.json`) it would be useful to include the git diff of just that directory.

Would you be open to doing `git diff HEAD .` (note the dot) instead? Could be an optional feature.

**Comment by novemberborn** [comment]
Interesting!

Currently we're looking for `.git/HEAD` relative to the `package.json`, which wouldn't work for monorepos. I suppose, since we're already reading the `package.json`, we could put some `package-hash` config in there to point at the repo root.

With that in place it's fine to do `git diff HEAD .`.

We could discover the repo root but that'll require more disk operations which we'd like to keep to a minimum. Especially since most of the time you'll be hashing packages from npm.

**Comment by vweevers** [comment]
I see. How about adding a `root` option? E.g. `hash('/monorepo/packages/a', { root: '/monorepo' })`. Would that work?

**Comment by novemberborn** [comment]
`package-hash` operates on other packages, typically dependencies of the calling code. The default mode is that such dependencies came from npm and the calling code just wants the hash to reflect changes. Probably because the hash is used as part of a cache key.

The more advanced mode is when you're developing the dependency and want to test it within the context of the parent package (the "calling code"). Typically the source code is in a Git repo and you `npm link` it into the parent package. Now it's useful if the hash changes as you're developing, so the parent package doesn't use any previously cached items.

The parent package doesn't know (or care) how the dependency was installed, or indeed what it's Git repo layout looks like. The root option can't be passed to `hash()`, it has to be resolved from the package that is being hashed. We'd have to support reading it from the `package.json` that's being hashed. In your example you, as a maintainer, would have to add it to `packages/beep/package.json`.

Hope that makes any sense?

Curious to know what your use case for `package-hash` is by the way.

**Comment by vweevers** [comment]
Thank you for the explanation. My intended usage doesn't fit that story exactly. I want hashes to reflect changes in a monorepo - as a whole or of individual nested package(s) - so expensive operations like installation can be skipped. Either locally, or on another machine - which probably necessitates another change to `package-hash`, namely to make included package paths relative. Additionally I'm including node ABI version, os and arch.

The caller is a "monorepo package manager" (somewhat like `lerna`). In this case, the subject of `package-hash` isn't a dependency of the caller. The caller has advance knowledge of the packages and the root location.

**Comment by novemberborn** [comment]
I don't think your requirements are in scope for `package-hash`. Feel free to extract the underlying code into a separate package though, perhaps `package-hash` could even depend on it.
